application: signinwithtwitter
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: latest

- name: django
  version: latest

handlers:
- url: .*
  script: main.py

